/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAX_H_RPCGEN
#define _MAX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct maxarray {
	int size;
	int arr[100];
};
typedef struct maxarray maxarray;

#define MAXARRAY_PROG 0x2f2f2f2f
#define MAXARRAY_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define max 1
extern  int * max_1(maxarray *, CLIENT *);
extern  int * max_1_svc(maxarray *, struct svc_req *);
extern int maxarray_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define max 1
extern  int * max_1();
extern  int * max_1_svc();
extern int maxarray_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_maxarray (XDR *, maxarray*);

#else /* K&R C */
extern bool_t xdr_maxarray ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAX_H_RPCGEN */
