/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "max.h"

int *
max_1_svc(maxarray *argp, struct svc_req *rqstp)
{
	static int  result;
	result = argp->arr[0];
	int n = argp->size;
	for(int i = 1 ; i < n ; i++)
	{
		if(result < argp->arr[i])
		result = argp->arr[i];
	}
	printf("Max element : %d\n", result);
	return &result;
}
