/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "max.h"


void
maxarray_prog_1(char *host, int n)
{
	CLIENT *clnt;
	int  *result_1;
	maxarray  max_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MAXARRAY_PROG, MAXARRAY_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	max_1_arg.size = n;	
	printf("Please enter %d elements : ", n);
	for (int i = 0; i < n; i++)
		scanf("%d", &max_1_arg.arr[i]);
	result_1 = max_1(&max_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("Largest element in the array : %d\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	char ch='y';
	int n=0;
	while (ch=='y')
	{
		system("clear");
		printf("Please enter size of array : ");
		scanf("%d", &n);
		if(n < 1 || n>100)
		{
			while (n<1)
			{
				printf("Please enter positive integer [1-100] : ");
				scanf("%d", &n);
			}
		}
		n%=101;
		maxarray_prog_1 (host, n);
		printf("Do you want to repeat ? (y/n) : ");
		scanf("%s", &ch);
	}
exit (0);
}
