/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "factorial.h"

int *
factorial_1_svc(number *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	
	int flag = 1;
	if(argp->num < 0)
	{
		printf("Factorial of negative numbers are not calculated!!!\n");
		flag = 0;
	}
	result = 1;
	for(int i = 2 ; i <= argp->num ; i++)
	result *= i;
	if(flag)
	printf("%d! = %d\n", argp->num, result);
	return &result;
}
