/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "birju.h"


void
exec_prog_1(char *host, int ch)
{
	CLIENT *clnt;
	output  *result_1;
	input  exec_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, EXEC_PROG, EXEC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	exec_1_arg.choice=ch;

	switch (ch)
	{
	case 1:
		printf("Please enter the string : ");
		scanf("%s", exec_1_arg.str1);
		break;

	case 2:
		printf("Please enter a year : ");
		scanf("%d", &exec_1_arg.year);
		break;

	case 3:
		printf("Please enter first integer  : ");
		scanf("%d", &exec_1_arg.num1);
		printf("Please enter second integer : ");
		scanf("%d", &exec_1_arg.num2);
		break;

	case 4:
		printf("Please enter a number : ");
		scanf("%d", &exec_1_arg.num1);
		break;
	
	case 5:
		printf("Please enter first number  : ");
		scanf("%d", &exec_1_arg.num1);
		printf("Please enter second number : ");
		scanf("%d", &exec_1_arg.num2);
		printf("Values before swap are : %d %d\n", exec_1_arg.num1, exec_1_arg.num2);
		break;

	case 6:
		printf("Please enter number of elements : ");
		scanf("%d", &exec_1_arg.year);
		printf("Please enter %d elements : ", exec_1_arg.year);
		for(int i = 0 ; i < exec_1_arg.year && i < 20; i++)
		{
			scanf("%d", &exec_1_arg.arr[i]);
		}
		break;
	case 7:
		printf("Please enter first string  : ");
		scanf("%s", exec_1_arg.str1);
		printf("Please enter second string : ");
		scanf("%s", exec_1_arg.str2);
		break;

	case 8:
		printf("Please enter first string  : ");
		scanf("%s", exec_1_arg.str1);
		printf("Please enter second string : ");
		scanf("%s", exec_1_arg.str2);
		break;
	
	case 9:
		printf("Please enter first string  : ");
		scanf("%s", exec_1_arg.str1);
		printf("Please enter second string : ");
		scanf("%s", exec_1_arg.str2);
		break;
	
	case 10:
		printf("Please enter number of elements : ");
		scanf("%d", &exec_1_arg.year);
		printf("Please enter %d elements : ", exec_1_arg.year);
		for(int i = 0 ; i < exec_1_arg.year ; i++)
		{
			scanf("%d", &exec_1_arg.arr[i]);
		}
		break;

	default:
		printf("Please enter a valid choice!!\n");
		return;
		break;
	}

	result_1 = exec_1(&exec_1_arg, clnt);
	if (result_1 == (output *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	switch (ch)
	{
	case 1:
		if(result_1->flag)
			printf("%s is Palindrome!!\n", exec_1_arg.str1);
		else
			printf("%s is not a Palindrome!!\n", exec_1_arg.str1);
		break;
	case 2:
		if(result_1->flag)
			printf("%d is a LEAP!!\n", exec_1_arg.year);
		else
			printf("%d is not LEAP!!\n", exec_1_arg.year);
		break;
	case 3:
		printf("GCD(%d,%d) : %d\n", exec_1_arg.num1, exec_1_arg.num2, result_1->gcd);
		break;
	case 4:
		printf("Square root of %d : %f\n", exec_1_arg.num1,result_1->sqrt);
		break;
	case 5:
		printf("Values after swap are : %d %d\n", result_1->num1, result_1->num2);
		break;
	case 6:
		printf("Maximum value in array : %d", result_1->max);
		printf("\nMinimum Value in array : %d", result_1->min);
		printf("\nAverage of all the values : %f\n", result_1->avg);
		break;
	case 7:
		if(result_1->flag > 0)
			printf("'%s' is greater than '%s'!!\n", exec_1_arg.str1, exec_1_arg.str2);	
		else if(result_1->flag == 0)
			printf("Both strings are same!!\n"); 
		else
			printf("'%s' is greater than '%s'!!\n", exec_1_arg.str2, exec_1_arg.str1);
		break;
	case 8:
		if(result_1->flag)
			printf("%s string is substring of %s!!\n", exec_1_arg.str2, exec_1_arg.str1);
		else
			printf("%s string is not substring of %s!!\n", exec_1_arg.str2, exec_1_arg.str1);
		break;
	case 9:
		printf("Concatenated string : %s\n", result_1->str);
		break;
	case 10:
		printf("Reverse of array : ");
		for(int i = 0 ; i < exec_1_arg.year ; i++)
			printf("%d ", result_1->arr[i]);
		printf("\n");
		break;
	default:
		printf("Bye Bye!!\n");
		return;
		break;
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int ch;
	char op='y';
	while (op=='y')
	{
		system("clear");
		printf("1  : To check if a string is palindrome.\n");
		printf("2  : Find if a year is leap.\n");
		printf("3  : find gcd of two number.\n");
		printf("4  : find square root of a given number.\n");
		printf("5  : Swap two variables without third variable.\n");
		printf("6  : Calculate maximum, mminimum and average.\n");
		printf("7  : Compare two strings.\n");
		printf("8  : Find whether a second string is substring.\n");
		printf("9  : Concatenate two strings.\n");
		printf("10 : Reverse elements of array.\n");
		printf("Please enter your choice : ");
		scanf("%d", &ch);
		exec_prog_1 (host,ch);
		printf("Do you want to continue? (y/n) : ");
		scanf("%s", &op);
	}
	printf("Hope you liked our service!!\n");
exit (0);
}
