/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prime.h"


void
prime_prog_1(char *host, int num1)
{
	CLIENT *clnt;
	int  *result_1;
	number  prime_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PRIME_PROG, PRIME_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	int flag = 1;
	prime_1_arg.num = num1;
	result_1 = prime_1(&prime_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	if(num1 < 1)
	{
		printf("Prime characteristic is only for Positive integers!!!!\n");
	}
	else
	{
		if(*result_1)
		{
			printf("%d is a PRIME!!\n", num1);
		}
		else
		{
			printf("%d is non-prime\n", num1);
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	char ch='y';
	int num;
	while(ch=='y')
	{
		system("clear");
		printf("Please enter an integer : ");
		scanf("%d", &num);
		prime_prog_1 (host, num);
		printf("Do you want to check more prime numbers ? (y/n) : ");
		scanf("%s", &ch);
	}
	
exit (0);
}
