/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prime.h"

int *
prime_1_svc(number *argp, struct svc_req *rqstp)
{
	static int  result;
	result=1;
	if(argp->num < 1)
	{
		printf("Entered number is not positive!!\n");
		result = 0;
		return &result;
	}
	else if(argp->num == 1)
	{
		printf("1 is non-prime!!!\n");
		result = 0;
		return &result;

	}
	int n = 1;
	while(n*n <= argp->num)
	n++;
	for(int i = 2 ; i <= n ; i++)
	{
		if(argp->num%i==0)
		{
			result = 0;
			printf("%d is non-prime!!!\n", argp->num);
			return &result;
		}
	}
	printf("%d is PRIME!!!\n", argp->num);
	return &result;
}
