/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculate.h"
 
float * calculate_1_svc(inputs *argp, struct svc_req *rqstp)
{
    static float result;
    float a = argp->num1;
    float b = argp->num2;
    char op = argp->operator;
    int flag = 1;
    if(op=='+')
        result = a+b;
    else if(op=='-')
        result = a-b;
    else if(op=='*')
        result = a*b;
    else
    {
        if(b==0)
        {
            printf("Division with 0 is invalid!!!\n");
            flag = 0;
        }
    }
    
    if(flag)
    printf("%f %c %f = %f\n",a, op, b, result);
    
    return &result;
}
