/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculate.h"


void
calculate_prog_1(char *host, float a, float b, char op)
{
	CLIENT *clnt;
	float  *result_1;
	inputs  calculate_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULATE_PROG, CALCULATE_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	calculate_1_arg.num1 = a;
	calculate_1_arg.num2 = b;
	calculate_1_arg.operator = op;

	result_1 = calculate_1(&calculate_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		int flag = 1;
		if(op=='/')
		{
			if(b==0)
			{
				printf("Division with 0 is invalid!!!\n");
				flag = 0;
			}
		}
		if(flag)
		{
			printf("%f %c %f = %f",a, op, b, *result_1);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	
	char op;
	float a, b;
	int ch=1;
	while(ch)
	{
		system("clear");
		printf("'+' : Addition\n");
		printf("'-' : Subtraction\n");
		printf("'*' : Multiplication\n");
		printf("'/' : Division\n");
		printf("Enter first number  : ");
		scanf("%f", &a);
		printf("Enter second number : ");
		scanf("%f", &b);
		printf("Enter operator : ");
		scanf("%s", &op);
		calculate_prog_1 (host, a, b, op);
		printf("\nDo calculations again ? (1/0) : ");
		scanf("%d", &ch);
	}
	printf("Hope you enjoyed our SERVICE!!\n");
exit (0);
}
