/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "birju.h"
#include <string.h>

int isPalindrome(char str[])
{
	int l=0;
	int h = strlen(str)-1;
	while (h>l)
	{
		if (str[l++] != str[h--])
        	return 0;
    }
    return 1;
}

int isLeap(int year)
{
	if(year%400==0 || (year%100!=0 && year%4 == 0))
		return 1;
	return 0;
}

int gcd1(int a, int b)
{
	if(a==0)
	    return b;
	return gcd1(b%a,a);
}

int isSubstr(char *str1,char *str2)
{
	int i=0,j;
	int n1=strlen(str1);
	int n2=strlen(str2);
	int flag;
	for (i = 0; i <= n1 - n2; i++)
    {
        for (j = i; j < i + n2; j++)
        {
            flag = 1;
            if (str1[j] != str2[j - i])
            {
                flag = 0;
                break;
            }
        }
        if (flag == 1)
            break;
    }
    return flag;
}

float findsqrt(float number)
{
	float temp, sq_rt;
	sq_rt = number / 2;
    temp = 0;
	while(sq_rt != temp){
        temp = sq_rt;
        sq_rt = ( number/temp + temp) / 2;
    }
	return sq_rt;
}

output *
exec_1_svc(input *argp, struct svc_req *rqstp)
{
	static output  result;

	int ch = argp->choice;
	switch (ch)
	{
	case 1:
		result.flag = isPalindrome(argp->str1);
		if(result.flag)
			printf("%s is Palindrome!!\n", argp->str1);
		else
			printf("%s is not a Palindrome!!\n", argp->str1);
		break;
	case 2:
		result.flag = isLeap(argp->year);
		if(result.flag)
			printf("%d is a LEAP!!\n", argp->year);
		else
			printf("%d is not a LEAP!!\n", argp->year);
		break;
	case 3:
		result.gcd = gcd1(argp->num1, argp->num2);
		printf("GCD[%d,%d] : %d\n", argp->num1, argp->num2, result.gcd);
		break;
	case 4:
		result.sqrt = findsqrt(argp->num1);
		printf("Square root of %d : %f\n", argp->num1, result.sqrt);
		break;
	case 5:
		result.num1 = argp->num2;
		result.num2 = argp->num1;
		printf("Numebers swapped successfully!!\n");
		break;
	case 6:
		result.min = argp->arr[0];
		result.max = argp->arr[0];
		result.avg = argp->arr[0];
		for(int i = 1 ; i < argp->year ; i++)
		{
			if(result.max < argp->arr[i])
			result.max = argp->arr[i];
			if(result.min > argp->arr[i])
			result.min = argp->arr[i];
			result.avg+=argp->arr[i];
		}
		result.avg/=argp->year;
		printf("MAX : %d", result.max);
		printf("\nMIN : %d", result.min);
		printf("\nAVG : %f\n", result.avg);
		break;
	case 7:
		result.flag = strcmp(argp->str1, argp->str2);
		if(result.flag > 0)
			printf("%s > %s\n", argp->str1, argp->str2);
		else if(result.flag == 0)
			printf("%s = %s\n", argp->str1, argp->str2);
		else
			printf("%s < %s\n", argp->str1, argp->str2);
		break;
	case 8:
		result.flag = isSubstr(argp->str1, argp->str2);
		if(result.flag)
			printf("%s is substring of %s\n", argp->str2, argp->str1);
		else
			printf("%s is not substring of %s\n", argp->str2, argp->str1);
		break;
	case 9:
		strcpy(result.str,"");
		strcat(result.str,argp->str1);
		strcat(result.str,argp->str2);
		printf("Concatenated string : %s\n", result.str);
		break;
	case 10:
		printf("Original array : ");
		for(int i = 0 ; i < argp->year ; i++)
		{
			printf("%d ", argp->arr[i]);
		}
		printf("\n");
		for(int i = 0 ; i < argp->year ; i++)
		{
			result.arr[i] = argp->arr[argp->year-1-i];
		}
		printf("Reverse array is : ");
		for(int i = 0 ; i < argp->year ; i++)
		{
			printf("%d ",result.arr[i]);
		}
		printf("\n");
		break;
	default:
		printf("Invalid input!!\n");
		break;
	}

	return &result;
}
