/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fib.h"

int *
fib_1_svc(fibonacci *argp, struct svc_req *rqstp)
{
	static int  result;

	int n=argp->n;
	if(n<=2)
		result=1;
	else
	{
		int cur=1,prev=1,i=2,temp;
		while(i<n)
		{
			temp=cur;
			cur=cur+prev;
			prev=temp;
			i++;
		}
		result=cur;
	}
	return &result;
}
