/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fib.h"


void
fib_prog_1(char *host, int n)
{
	CLIENT *clnt;
	int  *result_1;
	fibonacci  fib_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FIB_PROG, FIB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	fib_1_arg.n = 1;
	printf("Fibonacci series till %d : ", n);
	result_1 = fib_1(&fib_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		int i = 2;
		while (*result_1<n)
		{
			printf(" %d",*result_1);
			fib_1_arg.n=i;
			result_1 = fib_1(&fib_1_arg, clnt);
			i++;
		}
		printf("\n");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int n;
	char ch='y';
	while(ch=='y')
	{
		system("clear");
		printf("Enter a number : ");
		scanf("%d",&n);
		fib_prog_1 (host,n);
		printf("Do you want to repeat? (y/n): ");
		scanf("%s",&ch);
	}
exit (0);
}
